when@dev:
  monolog:
    use_microseconds: true
    channels: ["app"]
    handlers:
      app:
        type: stream
        path: php://stdout
        level: debug
        channels: ["app"]
        formatter: monolog.formatter.json
        include_stacktraces: true
      main:
        type: stream
        path: php://stdout
        level: debug
        channels: ["!event", "!app"]
        formatter: monolog.formatter.json
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine", "!console", "!app"]

when@test:
  monolog:
    handlers:
      main:
        type: stream
        path: php://stdout
        level: debug
        channels: ["!event"]
        formatter: monolog.formatter.json

when@prod:
  monolog:
    handlers:
      app:
        type: stream
        path: php://stdout
        level: notice
        channels: ["app"]
        formatter: monolog.formatter.json
      main:
        type: stream
        path: php://stdout
        level: error
        formatter: monolog.formatter.json
      nested:
        type: stream
        path: php://stdout
        level: debug
        formatter: monolog.formatter.json
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine"]
      deprecation:
        type: stream
        path: php://stdout
        channels: [deprecation]
        formatter: monolog.formatter.json
