when@dev:
  monolog:
    handlers:
      main:
        type: stream
        path: "php://stdout"
        level: debug
        channels: ["!event"]
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine", "!console"]

when@test:
  monolog:
    handlers:
      main:
        type: stream
        path: "php://stdout"
        level: debug
        channels: ["!event"]

when@prod:
  monolog:
    handlers:
      main:
        type: stream
        path: "php://stdout"
        level: error
        formatter: monolog.formatter.json
      nested:
        type: stream
        path: "php://stdout"
        level: debug
        formatter: monolog.formatter.json
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine"]
      deprecation:
        type: stream
        path: "php://stdout"
        channels: [deprecation]
        formatter: monolog.formatter.json
