nelmio_api_doc:
  documentation:
    servers:
      - url: http://localhost:8000
        description: API Server
    info:
      title: Provider Services API
      description: |
        REST API for managing service providers and their services.

        ## Features
        * Provider management (CRUD operations)
        * Service management (CRUD operations)
        * Redis caching
        * Comprehensive validation
      version: 1.0.0
      contact:
        name: API Support
        email: m.zoghlami@it-students.fr
    components:
      schemas:
        Error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
      responses:
        ValidationError:
          description: Validation error occurred
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        property:
                          type: string
                        message:
                          type: string
                        invalid_value:
                          type: string
  areas:
    path_patterns:
      - ^/api(?!/doc$)
  models:
    names:
      - { alias: Provider, type: App\DTO\Request\ProviderRequest }
      - { alias: UpdateProvider, type: App\DTO\Request\UpdateProviderRequest }
      - { alias: Service, type: App\DTO\Request\ServiceRequest }
      - { alias: UpdateService, type: App\DTO\Request\UpdateServiceRequest }
