services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql://db_user:db_password@db:3306/mydb
      REDIS_URL: redis://redis:6379
    platform: linux/arm64

  db:
    image: mysql:8.0
    container_name: mysql_db
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis_cache
    platform: linux/arm64
    ports:
      - "6379:6379"

volumes:
  db_data:
